app:
  gitlab:
    url: https://sys-urds.ofc.ru
    token: DurzRwyE3st7-xZtRCGE
    pr:
      userNames: kozub.an, lysenko_iv
#      authors:
#        -
#          id: 13
      skippPrDaysPassCount: 60d
      regularMessagesTtl: 1d
  telegram:
    token: 2101353204:AAG5BtDovNzEQxruLTfn5MQYaelGsY1dlQk
    botName: pr_gitlab_bot
    chatId: -1001698320025
    commentsChatId: -1001667252607
    proxyHost:
    proxyPort:
    proxyUser:
    proxyPassword:
  job:
    notifyAboutMergedPr: 0 * * * * *
    notifyAboutOpenedPr: '0 * * * * *'
    deleteRegularMessages: 0 0 8 * * *
    deleteTelegramComments: 0 * * * * *

spring:
  datasource:
    url: jdbc:h2:file:./db/pr_message;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  logging.file: /logs/pr-bot.log

